# draft conda environment file for simcmb

name: deepskies-simcmb

channels:
     - conda-forge/osx-64

dependencies:
     - python
     - numpy
     - matplotlib
     - camb
     - h5py
     - namaster
     - jupyter
     - pip
     - ipython

variables:
     - CONDA_SUBDIR: osx-64