USERPARAMS:
  FORCAMB:
#    InitPower:
#      r : 0.01
#    Alens : 1.0
    DoLensing : True
#    max_l : 10100
#    max_l_tensor : 10100
  rvals : [0.01, 0.1, 3]
  Avals : [.8, 1.2, 3]
  seed: 0
  verbose: 1
  cls_raw: False
  TT_dimension: muK
  outfile_dir: "outfiles"
  noise_type: "white"
  noise_level: 5 #uK*arcmin
  beam_fwhm: 3 #arcmin
  extra_l: 300
  max_l_use: 10000 # max_l_use will differ from max_l and max_l_tensor by "extra_l" because
  # according to the CAMB documentation errors affect the last "100 or so" multipoles

# see https://github.com/cmbant/CAMB/blob/master/inifiles/planck_2018.ini for detailed comments
# see documentation for relationship between the .yaml parameters and the .ini parameters
BASECAMBPARAMS:
  WantCls : True
  WantTransfer : False
  WantScalars : True
  WantTensors : True
  WantVectors : False
  WantDerivedParameters : True
  Want_cl_2D_array : True
  Want_CMB : True
  Want_CMB_lensing : True
#  DoLensing : True
  NonLinear : NonLinear_both
  Transfer:
    high_precision : True
    accurate_massive_neutrinos : False
    kmax : 0.9
    k_per_logint : 0
    PK_num_redshifts : 1
    PK_redshifts : [0.0]
  want_zstar : False
  want_zdrag : False
  min_l : 2
  max_l : 10500
  max_l_tensor : 10500
  max_eta_k : 28000.0
  max_eta_k_tensor : 28000.0
  ombh2 : 0.0223828
  omch2 : 0.1201075
  omk : 0.0
  omnuh2 : 0.0006451439
  H0 : 67.32117
  TCMB : 2.7255
  YHe : 0.2454006
  num_nu_massless : 2.046
  num_nu_massive : 1
  nu_mass_eigenstates : 1
  share_delta_neff : True
  nu_mass_degeneracies : [0.0]
  nu_mass_fractions : [1.0]
  nu_mass_numbers : [1]
  InitPower:
    tensor_parameterization : tensor_param_indeptilt
    ns : 0.9660499
    nrun : 0.0
    nrunrun : 0.0
    nt : 0.0
    ntrun : 0.0
#    r : 1.0
    pivot_scalar : 0.05
    pivot_tensor : 0.05
    As : 2.100549e-09
    At : 1.0
  Recomb:
    min_a_evolve_Tm : 0.0011098779505118728
    RECFAST_fudge : 1.125
    RECFAST_fudge_He : 0.86
    RECFAST_Heswitch : 6
    RECFAST_Hswitch : True
    AGauss1 : -0.14
    AGauss2 : 0.079
    zGauss1 : 7.28
    zGauss2 : 6.73
    wGauss1 : 0.18
    wGauss2 : 0.33
  Reion:
    Reionization : True
    use_optical_depth : True
    redshift : 10.0
    optical_depth : 0.05430842
    delta_redshift : 0.5
    fraction : -1.0
    include_helium_fullreion : True
    helium_redshift : 3.5
    helium_delta_redshift : 0.5
    helium_redshiftstart : 6.0
    tau_solve_accuracy_boost : 1.0
    timestep_boost : 1.0
    max_redshift : 50.0
  DarkEnergy:
    w : -1.0
    wa : 0.0
    cs2 : 1.0
    use_tabulated_w : False
  NonLinearModel:
    Min_kh_nonlinear : 0.005
    halofit_version : mead2016
    HMCode_A_baryon : 3.13
    HMCode_eta_baryon : 0.603
    HMCode_logT_AGN : 7.8
  Accuracy:
    AccuracyBoost : 1.0
    lSampleBoost : 1.0
    lAccuracyBoost : 1.0
    AccuratePolarization : True
    AccurateBB : False
    AccurateReionization : False
    TimeStepBoost : 1.0
    BackgroundTimeStepBoost : 1.0
    IntTolBoost : 1.0
    SourcekAccuracyBoost : 1.0
    IntkAccuracyBoost : 1.0
    TransferkBoost : 1.0
    NonFlatIntAccuracyBoost : 1.0
    BessIntBoost : 1.0
    LensingBoost : 1.0
    NonlinSourceBoost : 1.0
    BesselBoost : 1.0
    LimberBoost : 1.0
    SourceLimberBoost : 1.0
    KmaxBoost : 1.0
    neutrino_q_boost : 1.0
  SourceTerms:
    limber_windows : True
    limber_phi_lmin : 100
    counts_density : True
    counts_redshift : True
    counts_lensing : False
    counts_velocity : True
    counts_radial : False
    counts_timedelay : True
    counts_ISW : True
    counts_potential : True
    counts_evolve : False
    line_phot_dipole : False
    line_phot_quadrupole : False
    line_basic : True
    line_distortions : True
    line_extra : False
    line_reionization : False
    use_21cm_mK : True
  z_outputs : []
  scalar_initial_condition : initial_adiabatic
  InitialConditionVector : []
  OutputNormalization : 1
#  Alens : 1.0
  MassiveNuMethod : Nu_trunc
  DoLateRadTruncation : True
  Evolve_baryon_cs : False
  Evolve_delta_xe : False
  Evolve_delta_Ts : False
  Do21cm : False
  transfer_21cm_cl : False
  Log_lvalues : False
  use_cl_spline_template : True
  SourceWindows : []
  CustomSources:
    num_custom_sources : 0
    c_source_func : ~
    custom_source_ell_scales : []