
name: test-bench

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install conda
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        python -m ensurepip
        $CONDA/bin/conda env create -f conda-env.yml

    - name: Activate
      run: $CONDA/bin/conda activate deepskies-simcmb

    - name: Install package
      run: python3 -m pip install . 

    - name: Test with pytest
      run: |
       python3 -m pytest